In [1]:
import numpy as np
from PIL import Image
from matplotlib import pyplot as plt
from sklearn.neural_network import MLPClassifier
import os
import torch
import cv2
import tensorflow

In [24]:
labels = np.load('labels.npy',allow_pickle=True)
inputs = np.load('inputs.npy',allow_pickle=True)
inputs_labels = np.load('inputs_labels.npy',allow_pickle=True)

In [25]:
print(inputs_labels)

[array([[758.4787 , 227.24057,  93.32263, 151.15968,   8.41   ]])
 array([[344.01807, 206.18988,  27.3237 ,  54.85234,  23.02   ]])
 array([[906.59546 , 202.29488 ,  55.659363, 107.4476  ,  13.43    ],
        [656.03577 , 188.36948 ,  17.102234,  34.976547,  26.64    ],
        [255.35283 , 226.31586 ,  27.474335,  64.907364,  34.08    ]])
 array([[1048.7244  ,  226.95474 ,   56.736755,  154.70882 ,    4.1     ],
        [ 677.1876  ,  198.15646 ,   15.682922,   47.834442,    7.59    ],
        [ 698.7233  ,  193.37686 ,   21.066895,   47.46022 ,   24.14    ],
        [ 451.54282 ,  217.89337 ,   27.95404 ,   46.04979 ,   24.22    ]])]


In [26]:
print(inputs)

[array([[758.4787 , 227.24057,  93.32263, 151.15968]])
 array([[344.01807, 206.18988,  27.3237 ,  54.85234]])
 array([[906.59546 , 202.29488 ,  55.659363, 107.4476  ],
        [656.03577 , 188.36948 ,  17.102234,  34.976547],
        [255.35283 , 226.31586 ,  27.474335,  64.907364]])
 array([[1048.7244  ,  226.95474 ,   56.736755,  154.70882 ],
        [ 677.1876  ,  198.15646 ,   15.682922,   47.834442],
        [ 698.7233  ,  193.37686 ,   21.066895,   47.46022 ],
        [ 451.54282 ,  217.89337 ,   27.95404 ,   46.04979 ]])]


In [27]:
labels[2][0]

13.43

In [28]:
inputs_labels[:,0:4]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [13]:
model = MLPClassifier(
            hidden_layer_sizes=[10, 20],
            max_iter = 1000,
        )

In [14]:
model.fit(inputs, labels)

ValueError: setting an array element with a sequence.